"""
Tests for cmc_classification.classify_congruent_cells using test vectors
generated by MATLAB's cell_cmc_median (procedure 6).

The MATLAB reference is cell_cmc_median.m with:
  - Generalised ESD outlier rejection on cell angles
  - Median-based consensus angle and translation estimation
  - Final classification by similarity, angle, and position thresholds
"""

import json
from pathlib import Path

import numpy as np
import pytest

from conversion.surface_comparison.cmc_classification_consensus import (
    classify_congruent_cells_consensus,
)

from ..helpers import build_test_inputs


TEST_ROOT = Path(__file__).parent.parent.parent.parent
RESOURCES_DIR = TEST_ROOT / "resources"
TEST_DATA_PATH = RESOURCES_DIR / "cmc" / "classification" / "cmc_test_data.json"


ANGLE_ATOL = 1e-10
TRANSLATION_ATOL = 1e-10


def _load_test_cases() -> list[dict]:
    with open(TEST_DATA_PATH) as f:
        return json.load(f)


# we skip these cases since results are based on cmc median method and output from consensus method
_EXCLUDED_CASES = {
    "low_similarity_cells",
    "no_valid_cells",
    "angle_outliers_esd_rejection",
    "position_outliers",
    "mixed_outliers",
    "all_angle_outliers",
    "nan_similarity_values",
}

_TEST_CASES = [c for c in _load_test_cases() if c["name"] not in _EXCLUDED_CASES]
_TEST_IDS = [test_case["name"] for test_case in _TEST_CASES]


@pytest.fixture(params=_TEST_CASES, ids=_TEST_IDS)
def matlab_test_case(request) -> dict:
    return request.param


def _get_case(name: str) -> dict:
    for test_case in _TEST_CASES:
        if test_case["name"] == name:
            return test_case
    raise ValueError(f"Test case '{name}' not found")


class TestClassifyCongruentCells:
    """Test classify_congruent_cells against MATLAB cell_cmc_median procedure 6."""

    def test_cmc_count(self, matlab_test_case: dict) -> None:
        """The number of CMC cells must match the MATLAB reference."""
        cells, params, rotation_center_reference = build_test_inputs(
            matlab_test_case["inputs"]
        )

        result = classify_congruent_cells_consensus(
            cells, params, rotation_center_reference
        )

        expected_cmc_count = matlab_test_case["outputs"]["cmc_count"]
        assert result.cmc_count == expected_cmc_count, (
            f"[{matlab_test_case['name']}] CMC count mismatch: "
            f"expected {expected_cmc_count}, got {result.cmc_count}"
        )

    def test_cmc_flags(self, matlab_test_case: dict) -> None:
        """Per-cell congruence flags must match the MATLAB reference."""
        cells, params, rotation_center_reference = build_test_inputs(
            matlab_test_case["inputs"]
        )

        result = classify_congruent_cells_consensus(
            cells, params, rotation_center_reference
        )

        expected_flags = matlab_test_case["outputs"]["is_congruent"]
        if isinstance(expected_flags, bool):
            expected_flags = [expected_flags]
        actual_flags = [cell.is_congruent for cell in result.cells]
        assert actual_flags == expected_flags, (
            f"[{matlab_test_case['name']}] Congruence flags mismatch:\n"
            f"  expected: {expected_flags}\n"
            f"  actual:   {actual_flags}"
        )

    def test_consensus_rotation(self, matlab_test_case: dict) -> None:
        """The consensus rotation must match the MATLAB reference."""

        # we skip this test since results are based on the median cmc method and are therefore expected to be different
        if matlab_test_case["name"] == "all_congruent_no_outliers":
            pytest.skip("consensus rotation not tested for all_congruent_no_outliers")

        cells, params, rotation_center_reference = build_test_inputs(
            matlab_test_case["inputs"]
        )

        result = classify_congruent_cells_consensus(
            cells, params, rotation_center_reference
        )

        expected_rotation = matlab_test_case["outputs"]["consensus_rotation_deg"]
        if np.isnan(expected_rotation):
            assert np.isnan(result.shared_rotation), (
                f"[{matlab_test_case['name']}] Expected NaN consensus rotation, "
                f"got {result.shared_rotation}"
            )
        else:
            np.testing.assert_allclose(
                result.shared_rotation,
                expected_rotation,
                atol=ANGLE_ATOL,
                err_msg=f"[{matlab_test_case['name']}] Consensus rotation mismatch",
            )

    def test_consensus_translation(self, matlab_test_case: dict) -> None:
        """The consensus translation must match the MATLAB reference.
        The matlab code works with a mathematical coordinate system (with origine bottom-left), while our pipeline
        works with a image coordinate system. Therefore, we reflect the y-axis, the y-coordinate of the rotation center
        and the resulting y-translation. This reproduces the Matlab results.
        """

        # we skip this test since results are based on the median cmc method and are therefore expected to be different
        if matlab_test_case["name"] == "all_congruent_no_outliers":
            pytest.skip("consensus rotation not tested for all_congruent_no_outliers")

        cells, params, rotation_center_reference = build_test_inputs(
            matlab_test_case["inputs"]
        )

        result = classify_congruent_cells_consensus(
            cells, params, rotation_center_reference
        )

        expected_translation = matlab_test_case["outputs"]["consensus_translation"]
        actual_translation = result.shared_translation
        actual_translation_list = list(actual_translation)
        actual_translation = (
            actual_translation_list[0],
            -1 * actual_translation_list[1],
        )
        if all(item is None for item in expected_translation):
            assert all(np.isnan(v) for v in actual_translation), (
                f"[{matlab_test_case['name']}] Expected NaN translation, "
                f"got {actual_translation}"
            )
        else:
            np.testing.assert_allclose(
                np.array(actual_translation),
                np.array(expected_translation),
                atol=TRANSLATION_ATOL,
                err_msg=f"[{matlab_test_case['name']}] Consensus translation mismatch",
            )


class TestSpecificScenarios:
    """Named tests per scenario, useful for targeted debugging of failure modes."""

    def test_all_congruent_no_outliers(self) -> None:
        """All cells share a consistent transformation — all should be CMC."""
        # Arrange
        cells, params, rotation_center_reference = build_test_inputs(
            _get_case("all_congruent_no_outliers")["inputs"]
        )

        # Act
        result = classify_congruent_cells_consensus(
            cells, params, rotation_center_reference
        )

        # Assert
        assert all(cell.is_congruent for cell in result.cells)
        assert result.cmc_count == 6

    def test_single_cell(self) -> None:
        """A single valid cell should be classified as CMC."""
        # Arrange
        cells, params, rotation_center_reference = build_test_inputs(
            _get_case("single_cell")["inputs"]
        )

        # Act
        result = classify_congruent_cells_consensus(
            cells, params, rotation_center_reference
        )

        # Assert
        assert result.cells[0].is_congruent
