"""
Tests for cmc_classification.classify_congruent_cells using test vectors
generated by MATLAB's cell_cmc_median (procedure 6).

The MATLAB reference is cell_cmc_median.m with:
  - Generalised ESD outlier rejection on cell angles
  - Median-based consensus angle and translation estimation
  - Final classification by similarity, angle, and position thresholds
"""

import json
import math
from pathlib import Path

import numpy as np
import pytest

from conversion.surface_comparison.cmc_consensus.criterion import calculate_criterion
from conversion.surface_comparison.cmc_consensus.pipeline import (
    _get_cell_angle_and_position_distances,
    _refine,
    classify_congruent_cells_consensus,
)
from conversion.surface_comparison.models import Cell, CellMetaData

from ..helpers import build_test_inputs


TEST_ROOT = Path(__file__).parent.parent.parent.parent
RESOURCES_DIR = TEST_ROOT / "resources"
TEST_DATA_PATH = RESOURCES_DIR / "cmc" / "classification" / "cmc_test_data.json"


ANGLE_ATOL = 1e-10
TRANSLATION_ATOL = 1e-10


def _load_test_cases() -> list[dict]:
    with open(TEST_DATA_PATH) as f:
        return json.load(f)


# we skip these cases since results are based on cmc median method and output from consensus method
_EXCLUDED_CASES = {
    "low_similarity_cells",
    "no_valid_cells",
    "angle_outliers_esd_rejection",
    "position_outliers",
    "mixed_outliers",
    "all_angle_outliers",
    "nan_similarity_values",
}

_TEST_CASES = [c for c in _load_test_cases() if c["name"] not in _EXCLUDED_CASES]
_TEST_IDS = [test_case["name"] for test_case in _TEST_CASES]


@pytest.fixture(params=_TEST_CASES, ids=_TEST_IDS)
def matlab_test_case(request) -> dict:
    return request.param


def _get_case(name: str) -> dict:
    for test_case in _TEST_CASES:
        if test_case["name"] == name:
            return test_case
    raise ValueError(f"Test case '{name}' not found")


class TestClassifyCongruentCells:
    """Test classify_congruent_cells against MATLAB cell_cmc_median procedure 6."""

    def test_cmc_count(self, matlab_test_case: dict) -> None:
        """The number of CMC cells must match the MATLAB reference."""

        # Arrange
        expected_cmc_count = matlab_test_case["outputs"]["cmc_count"]
        cells, params, rotation_center_reference = build_test_inputs(
            matlab_test_case["inputs"]
        )

        # Act
        result = classify_congruent_cells_consensus(
            cells, params, rotation_center_reference
        )

        # Assert
        assert result.cmc_count == expected_cmc_count, (
            f"[{matlab_test_case['name']}] CMC count mismatch: "
            f"expected {expected_cmc_count}, got {result.cmc_count}"
        )

    def test_cmc_flags(self, matlab_test_case: dict) -> None:
        """Per-cell congruence flags must match the MATLAB reference."""

        # Arrange
        expected_flags = matlab_test_case["outputs"]["is_congruent"]
        cells, params, rotation_center_reference = build_test_inputs(
            matlab_test_case["inputs"]
        )

        # Act
        result = classify_congruent_cells_consensus(
            cells, params, rotation_center_reference
        )

        # Assert
        if isinstance(expected_flags, bool):
            expected_flags = [expected_flags]
        actual_flags = [cell.is_congruent for cell in result.cells]
        assert actual_flags == expected_flags, (
            f"[{matlab_test_case['name']}] Congruence flags mismatch:\n"
            f"  expected: {expected_flags}\n"
            f"  actual:   {actual_flags}"
        )

    def test_consensus_rotation(self, matlab_test_case: dict) -> None:
        """The consensus rotation must match the MATLAB reference."""

        # we skip this test since results are based on the median cmc method and are therefore expected to be different
        if matlab_test_case["name"] == "all_congruent_no_outliers":
            pytest.skip("consensus rotation not tested for all_congruent_no_outliers")

        # Arrange
        expected_rotation = matlab_test_case["outputs"]["consensus_rotation_deg"]
        cells, params, rotation_center_reference = build_test_inputs(
            matlab_test_case["inputs"]
        )

        # Act
        result = classify_congruent_cells_consensus(
            cells, params, rotation_center_reference
        )

        # Assert
        if np.isnan(expected_rotation):
            assert np.isnan(result.estimated_rotation), (
                f"[{matlab_test_case['name']}] Expected NaN consensus rotation, "
                f"got {result.estimated_rotation}"
            )
        else:
            np.testing.assert_allclose(
                result.estimated_rotation,
                expected_rotation,
                atol=ANGLE_ATOL,
                err_msg=f"[{matlab_test_case['name']}] Consensus rotation mismatch",
            )

    def test_consensus_translation(self, matlab_test_case: dict) -> None:
        """The consensus translation must match the MATLAB reference.
        The matlab code works with a mathematical coordinate system (with origine bottom-left), while our pipeline
        works with a image coordinate system. Therefore, we reflect the y-axis, the y-coordinate of the rotation center
        and the resulting y-translation. This reproduces the Matlab results.
        """

        # we skip this test since results are based on the median cmc method and are therefore expected to be different
        if matlab_test_case["name"] == "all_congruent_no_outliers":
            pytest.skip("consensus rotation not tested for all_congruent_no_outliers")

        # Arrange
        expected_translation = matlab_test_case["outputs"]["consensus_translation"]
        cells, params, rotation_center_reference = build_test_inputs(
            matlab_test_case["inputs"]
        )

        # Act
        result = classify_congruent_cells_consensus(
            cells, params, rotation_center_reference
        )

        actual_translation = result.estimated_translation
        actual_translation_list = list(actual_translation)
        actual_translation = (
            actual_translation_list[0],
            -1 * actual_translation_list[1],
        )

        # Assert
        if all(item is None for item in expected_translation):
            assert all(np.isnan(v) for v in actual_translation), (
                f"[{matlab_test_case['name']}] Expected NaN translation, "
                f"got {actual_translation}"
            )
        else:
            np.testing.assert_allclose(
                np.array(actual_translation),
                np.array(expected_translation),
                atol=TRANSLATION_ATOL,
                err_msg=f"[{matlab_test_case['name']}] Consensus translation mismatch",
            )


class TestSpecificScenarios:
    """Named tests per scenario, useful for targeted debugging of failure modes."""

    def test_all_congruent_no_outliers(self) -> None:
        """All cells share a consistent transformation — all should be CMC."""
        # Arrange
        cells, params, rotation_center_reference = build_test_inputs(
            _get_case("all_congruent_no_outliers")["inputs"]
        )

        # Act
        result = classify_congruent_cells_consensus(
            cells, params, rotation_center_reference
        )

        # Assert
        assert all(cell.is_congruent for cell in result.cells)
        assert result.cmc_count == 6

    def test_single_cell(self) -> None:
        """A single valid cell should be classified as CMC."""
        # Arrange
        cells, params, rotation_center_reference = build_test_inputs(
            _get_case("single_cell")["inputs"]
        )

        # Act
        result = classify_congruent_cells_consensus(
            cells, params, rotation_center_reference
        )

        # Assert
        assert result.cells[0].is_congruent


class TestRefineReturnsUpdatedValues:
    """Tests that _refine actually modifies the inlier set (verifies the return-value fix)."""

    @pytest.fixture
    def cells_with_consistent_group(self) -> list[Cell]:
        """Create cells with a realistic pattern: a consistent group plus one outlier.

        Cells 0-3 share a consistent transformation (~-1° rotation + small translation) with small realistic variations.
        Their angle_deg values (~1°) match the expected rotation. Cell 4 is a clear outlier with different
        angle/position.

        The angle distance formula is abs(angle_deg + consensus_rotation_deg), so consistent cells have
        angle_deg ≈ -consensus_rotation_deg.
        """
        meta = CellMetaData(
            is_outlier=False, residual_angle_deg=0.0, position_error=(0.0, 0.0)
        )

        def apply_transform(ref: tuple[float, float]) -> tuple[float, float]:
            """Apply -1° rotation + small translation to a reference center."""
            angle_rad = math.radians(-1.0)
            cos_a, sin_a = math.cos(angle_rad), math.sin(angle_rad)
            x, y = ref
            return (x * cos_a - y * sin_a + 5e-5, x * sin_a + y * cos_a - 3e-5)

        return [
            Cell(
                center_reference=(0.001, 0.001),
                center_comparison=apply_transform((0.001, 0.001)),
                angle_deg=1.0,
                best_score=0.9,
                cell_size=(4.5e-4, 4.5e-4),
                fill_fraction_reference=1.0,
                is_congruent=False,
                meta_data=meta.model_copy(),
            ),
            Cell(
                center_reference=(0.002, 0.001),
                center_comparison=apply_transform((0.002, 0.001)),
                angle_deg=1.1,
                best_score=0.9,
                cell_size=(4.5e-4, 4.5e-4),
                fill_fraction_reference=1.0,
                is_congruent=False,
                meta_data=meta.model_copy(),
            ),
            Cell(
                center_reference=(0.003, 0.001),
                center_comparison=apply_transform((0.003, 0.001)),
                angle_deg=0.9,
                best_score=0.9,
                cell_size=(4.5e-4, 4.5e-4),
                fill_fraction_reference=1.0,
                is_congruent=False,
                meta_data=meta.model_copy(),
            ),
            Cell(
                center_reference=(0.001, 0.002),
                center_comparison=apply_transform((0.001, 0.002)),
                angle_deg=1.0,
                best_score=0.9,
                cell_size=(4.5e-4, 4.5e-4),
                fill_fraction_reference=1.0,
                is_congruent=False,
                meta_data=meta.model_copy(),
            ),
            # Cell 4: clear outlier with very different angle and position
            Cell(
                center_reference=(0.002, 0.002),
                center_comparison=(0.0035, 0.0035),
                angle_deg=30.0,
                best_score=0.9,
                cell_size=(4.5e-4, 4.5e-4),
                fill_fraction_reference=1.0,
                is_congruent=False,
                meta_data=meta.model_copy(),
            ),
        ]

    def test_refine_grows_inlier_set(
        self, cells_with_consistent_group: list[Cell]
    ) -> None:
        """Refinement re-fits consensus and pulls in additional consistent cells."""
        # Arrange: start with just cells 0 and 1 as initial inliers (pair-based solution)
        initial_ids = [0, 1]
        cell_distances, cell_angle_distances = _get_cell_angle_and_position_distances(
            initial_ids, cells_with_consistent_group
        )
        initial_criterion = calculate_criterion(
            cell_distances[initial_ids],
            cell_angle_distances[initial_ids],
            max_distance=0.0001,
            max_abs_angle_distance=2.0,
        )

        # Act
        refined_ids, refined_criterion = _refine(
            current_ids=initial_ids,
            criterion_current=initial_criterion,
            cells=cells_with_consistent_group,
            max_distance=0.0001,
            max_abs_angle_distance=2.0,
        )

        # Assert: refinement should have pulled in cells 2 and 3, excluded outlier cell 4
        assert len(refined_ids) > len(initial_ids), (
            "Refinement should grow the inlier set"
        )
        assert set(refined_ids) == {0, 1, 2, 3}, (
            f"Refinement should include all consistent cells and exclude the outlier, got {refined_ids}"
        )
        # Cells 2 and 3 sit on the same transform, so they grow the set without moving the criterion
        assert refined_criterion == pytest.approx(initial_criterion)

    def test_refine_improves_criterion(
        self, cells_with_consistent_group: list[Cell]
    ) -> None:
        """Refinement improves the criterion as it re-fits."""
        # Arrange: start with a subset that already captures most of the group
        initial_ids = [0, 1, 2]
        cell_distances, cell_angle_distances = _get_cell_angle_and_position_distances(
            initial_ids, cells_with_consistent_group
        )
        initial_criterion = calculate_criterion(
            cell_distances[initial_ids],
            cell_angle_distances[initial_ids],
            max_distance=0.0001,
            max_abs_angle_distance=2.0,
        )

        # Act
        refined_ids, refined_criterion = _refine(
            current_ids=initial_ids,
            criterion_current=initial_criterion,
            cells=cells_with_consistent_group,
            max_distance=0.0001,
            max_abs_angle_distance=2.0,
        )

        # Assert: should pull in cell 3 and improve criterion
        assert 3 in refined_ids, "Refinement should include cell 3 which is consistent"
        assert refined_criterion < initial_criterion, (
            "Criterion should improve after refinement"
        )

    def test_refine_returns_converged_when_no_improvement(
        self, cells_with_consistent_group: list[Cell]
    ) -> None:
        """Refinement returns unchanged when already at a local optimum."""
        # Arrange: start with the full optimal set
        initial_ids = [0, 1, 2, 3]
        cell_distances, cell_angle_distances = _get_cell_angle_and_position_distances(
            initial_ids, cells_with_consistent_group
        )
        initial_criterion = calculate_criterion(
            cell_distances[initial_ids],
            cell_angle_distances[initial_ids],
            max_distance=0.0001,
            max_abs_angle_distance=2.0,
        )

        # Act
        refined_ids, refined_criterion = _refine(
            current_ids=initial_ids,
            criterion_current=initial_criterion,
            cells=cells_with_consistent_group,
            max_distance=0.0001,
            max_abs_angle_distance=2.0,
        )

        # Assert: no improvement possible, should return as-is
        assert refined_ids == initial_ids
        assert refined_criterion == initial_criterion
