"""
Tests for cmc_classification.classify_congruent_cells using test vectors
generated by MATLAB's cell_cmc_median (procedure 6).

The MATLAB reference is cell_cmc_median.m with:
  - Generalized ESD outlier rejection on cell angles
  - Median-based consensus angle and translation estimation
  - Final classification by similarity, angle, and position thresholds
"""

import json
from pathlib import Path

import numpy as np
import pytest

from conversion.surface_comparison.cmc_classification import (
    classify_congruent_cells,
)
from conversion.surface_comparison.models import (
    Cell,
    ComparisonParams,
    ComparisonResult,
)


TEST_DATA_PATH = Path(__file__).parent / "cmc_test_data_degrees.json"


def _load_test_cases() -> list[dict]:
    with open(TEST_DATA_PATH) as f:
        return json.load(f)


def _as_array(value, dtype=np.float64) -> np.ndarray:
    """Convert a JSON value (which may contain ``None`` for NaN) to an array."""
    if value is None:
        return np.array([np.nan], dtype=dtype)
    if isinstance(value, (int, float)):
        return np.array([value], dtype=dtype)

    def _replace_none(v):
        if v is None:
            return np.nan
        return v

    if isinstance(value, list) and value and isinstance(value[0], list):
        return np.array([[_replace_none(x) for x in row] for row in value], dtype=dtype)
    return np.array([_replace_none(x) for x in value], dtype=dtype)


def _build_comparison_result(
    inputs: dict,
) -> tuple[ComparisonResult, ComparisonParams, np.ndarray]:
    """
    Build a ComparisonResult populated with CellResult objects and a
    ComparisonParams from a single MATLAB test-case input dict.

    Returns ``(result, params, global_center)``.

    MATLAB field mapping
    --------------------
    ============== ====================================================
    MATLAB field   Python CellResult field
    ============== ====================================================
    vPos1          center_reference
    vPos2          center_comparison
    angle2-angle1  registration_angle  (delta; angle1 is always 0 in
                   our test data so registration_angle == angle2)
    simVal         area_cross_correlation_function_score
    ============== ====================================================
    """
    mPos1 = _as_array(inputs["mPos1"])
    mPos2 = _as_array(inputs["mPos2"])
    angle1 = _as_array(inputs["angle1"])
    angle2 = _as_array(inputs["angle2"])
    sim_vals = _as_array(inputs["simVals"])

    # Handle single-cell case where JSON gives 1-D arrays
    if mPos1.ndim == 1:
        mPos1 = mPos1.reshape(1, -1)
        mPos2 = mPos2.reshape(1, -1)
    if angle1.ndim == 0:
        angle1 = angle1.reshape(1)
        angle2 = angle2.reshape(1)
        sim_vals = sim_vals.reshape(1)

    n_cells = mPos1.shape[0]

    cells = []
    for i in range(n_cells):
        angle_val = float(angle2[i] - angle1[i])
        score_val = float(sim_vals[i])
        cell = Cell(
            cell_data=np.array([[0.0, 0.0], [0.1, 0.1]]),
            center_reference=mPos1[i],
            center_comparison=mPos2[i],
            # registration_angle is the delta: angle2 - angle1
            angle_reference=None if np.isnan(angle_val) else angle_val,
            best_score=None if np.isnan(score_val) else score_val,
            fill_fraction_reference=1.0,
        )
        cells.append(cell)

    result = ComparisonResult()
    result.cells = cells

    params = ComparisonParams(
        correlation_threshold=inputs["simMin"],
        angle_threshold=inputs["angleMax"],
        position_threshold=inputs["distMax"],
    )

    global_center = np.array(inputs["vCenter"], dtype=np.float64)

    return result, params, global_center


_TEST_CASES = _load_test_cases()
_TEST_IDS = [tc["name"] for tc in _TEST_CASES]


@pytest.fixture(params=_TEST_CASES, ids=_TEST_IDS)
def matlab_test_case(request):
    return request.param


class TestClassifyCongruentCells:
    """Test classify_congruent_cells against MATLAB cell_cmc_median procedure 6."""

    def test_cmc_count(self, matlab_test_case):
        """The number of CMC cells must match the MATLAB reference."""
        tc = matlab_test_case
        result, params, center = _build_comparison_result(tc["inputs"])

        classify_congruent_cells(result, params, center)

        expected_n = tc["outputs"]["nCmc"]
        actual_n = sum(1 for c in result.cells if c.is_congruent)
        assert actual_n == expected_n, (
            f"[{tc['name']}] CMC count mismatch: expected {expected_n}, got {actual_n}"
        )

    def test_cmc_flags(self, matlab_test_case):
        """Per-cell CMC flags must match the MATLAB reference."""
        tc = matlab_test_case
        result, params, center = _build_comparison_result(tc["inputs"])

        classify_congruent_cells(result, params, center)

        expected_flags = tc["outputs"]["vbVal"]
        if isinstance(expected_flags, bool):
            expected_flags = [expected_flags]

        actual_flags = [c.is_congruent for c in result.cells]
        assert actual_flags == expected_flags, (
            f"[{tc['name']}] CMC flags mismatch:\n"
            f"  expected: {expected_flags}\n"
            f"  actual:   {actual_flags}"
        )

    def test_consensus_rotation(self, matlab_test_case):
        """The consensus rotation must match the MATLAB rAngle."""
        tc = matlab_test_case
        result, params, center = _build_comparison_result(tc["inputs"])

        classify_congruent_cells(result, params, center)

        expected_angle = tc["outputs"]["rAngle"]
        actual_angle = result.consensus_rotation

        if np.isnan(expected_angle):
            assert np.isnan(actual_angle), (
                f"[{tc['name']}] Expected NaN consensus rotation, got {actual_angle}"
            )
        else:
            np.testing.assert_allclose(
                actual_angle,
                expected_angle,
                atol=1e-10,
                err_msg=f"[{tc['name']}] Consensus rotation mismatch",
            )

    def test_consensus_translation(self, matlab_test_case):
        """The consensus translation must match the MATLAB vTrans."""
        tc = matlab_test_case
        result, params, center = _build_comparison_result(tc["inputs"])

        classify_congruent_cells(result, params, center)

        expected_trans = _as_array(tc["outputs"]["vTrans"])
        actual_trans = np.asarray(result.consensus_translation)

        if np.all(np.isnan(expected_trans)):
            assert np.all(np.isnan(actual_trans)), (
                f"[{tc['name']}] Expected NaN translation, got {actual_trans}"
            )
        else:
            np.testing.assert_allclose(
                actual_trans,
                expected_trans,
                atol=1e-10,
                err_msg=f"[{tc['name']}] Consensus translation mismatch",
            )


class TestSpecificScenarios:
    """
    Named tests for each scenario, useful for quick debugging of
    individual failure modes.
    """

    @staticmethod
    def _get_case(name: str) -> dict:
        for tc in _TEST_CASES:
            if tc["name"] == name:
                return tc
        raise ValueError(f"Test case '{name}' not found")

    def test_all_congruent_no_outliers(self):
        """All cells share a consistent transformation — all should be CMC."""
        tc = self._get_case("all_congruent_no_outliers")
        result, params, center = _build_comparison_result(tc["inputs"])
        classify_congruent_cells(result, params, center)
        assert all(c.is_congruent for c in result.cells)
        assert sum(1 for c in result.cells if c.is_congruent) == 6

    def test_low_similarity_rejected(self):
        """Cells below the correlation threshold must not be classified as CMC."""
        tc = self._get_case("low_similarity_cells")
        result, params, center = _build_comparison_result(tc["inputs"])
        classify_congruent_cells(result, params, center)
        # Cells at index 1 and 3 have simVal 0.2 and 0.15 (below 0.4)
        assert not result.cells[1].is_congruent
        assert not result.cells[3].is_congruent
        assert sum(1 for c in result.cells if c.is_congruent) == 4

    def test_esd_rejects_angle_outliers(self):
        """ESD outlier rejection should remove cells with aberrant angles."""
        tc = self._get_case("angle_outliers_esd_rejection")
        result, params, center = _build_comparison_result(tc["inputs"])
        classify_congruent_cells(result, params, center)
        # Cells 3 and 7 (0-indexed: 2 and 6) are angle outliers
        assert not result.cells[2].is_congruent
        assert not result.cells[6].is_congruent
        assert sum(1 for c in result.cells if c.is_congruent) == 6

    def test_position_outliers_rejected(self):
        """Cells with large position residuals must be rejected."""
        tc = self._get_case("position_outliers")
        result, params, center = _build_comparison_result(tc["inputs"])
        classify_congruent_cells(result, params, center)
        # Cells 2 and 5 (0-indexed: 1 and 4) have large position errors
        assert not result.cells[1].is_congruent
        assert not result.cells[4].is_congruent
        assert sum(1 for c in result.cells if c.is_congruent) == 4

    def test_no_valid_cells(self):
        """When all cells are below similarity threshold, zero CMCs result."""
        tc = self._get_case("no_valid_cells")
        result, params, center = _build_comparison_result(tc["inputs"])
        classify_congruent_cells(result, params, center)
        assert not any(c.is_congruent for c in result.cells)

    def test_mixed_outliers(self):
        """Mixed failure modes: similarity, angle, and position outliers."""
        tc = self._get_case("mixed_outliers")
        result, params, center = _build_comparison_result(tc["inputs"])
        classify_congruent_cells(result, params, center)
        # Cell 2 (idx 1): low sim, Cell 4 (idx 3): angle, Cell 8 (idx 7): pos
        assert not result.cells[1].is_congruent
        assert not result.cells[3].is_congruent
        assert not result.cells[7].is_congruent
        assert sum(1 for c in result.cells if c.is_congruent) == 7

    def test_single_cell(self):
        """A single valid cell should be classified as CMC."""
        tc = self._get_case("single_cell")
        result, params, center = _build_comparison_result(tc["inputs"])
        classify_congruent_cells(result, params, center)
        assert result.cells[0].is_congruent

    def test_all_angle_outliers_no_cmc(self):
        """When all angles are wildly scattered, ESD + filtering yields 0 CMC."""
        tc = self._get_case("all_angle_outliers")
        result, params, center = _build_comparison_result(tc["inputs"])
        classify_congruent_cells(result, params, center)
        assert not any(c.is_congruent for c in result.cells)

    def test_nan_similarity_handled(self):
        """Cells with NaN similarity (failed registration) must not be CMC."""
        tc = self._get_case("nan_similarity_values")
        result, params, center = _build_comparison_result(tc["inputs"])
        classify_congruent_cells(result, params, center)
        # Cells 2 and 5 (0-indexed: 1 and 4) have NaN
        assert not result.cells[1].is_congruent
        assert not result.cells[4].is_congruent
        assert sum(1 for c in result.cells if c.is_congruent) == 4
