"""
Tests for cmc_classification.classify_congruent_cells using test vectors
generated by MATLAB's cell_cmc_median (procedure 6).

The MATLAB reference is cell_cmc_median.m with:
  - Generalised ESD outlier rejection on cell angles
  - Median-based consensus angle and translation estimation
  - Final classification by similarity, angle, and position thresholds
"""

import json
from pathlib import Path

import numpy as np
import pytest

from conversion.surface_comparison.cmc_classification import classify_congruent_cells

from .helpers import as_array, build_test_params


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TEST_DATA_PATH = (
    Path(__file__).parent.parent.parent
    / "resources"
    / "cmc"
    / "classification"
    / "cmc_test_data_degrees.json"
)

ANGLE_ATOL = 1e-10
TRANSLATION_ATOL = 1e-10


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


def _load_test_cases() -> list[dict]:
    with open(TEST_DATA_PATH) as f:
        return json.load(f)


_TEST_CASES = _load_test_cases()
_TEST_IDS = [tc["name"] for tc in _TEST_CASES]


@pytest.fixture(params=_TEST_CASES, ids=_TEST_IDS)
def matlab_test_case(request):
    return request.param


# ---------------------------------------------------------------------------
# Parametrised tests against MATLAB reference
# ---------------------------------------------------------------------------


class TestClassifyCongruentCells:
    """Test classify_congruent_cells against MATLAB cell_cmc_median procedure 6."""

    def test_cmc_count(self, matlab_test_case):
        """The number of CMC cells must match the MATLAB reference."""
        tc = matlab_test_case
        cells, params, center = build_test_params(tc["inputs"])

        result = classify_congruent_cells(cells, params, center)

        expected_n = tc["outputs"]["nCmc"]
        actual_n = result.cmc_count
        assert actual_n == expected_n, (
            f"[{tc['name']}] CMC count mismatch: expected {expected_n}, got {actual_n}"
        )

    def test_cmc_flags(self, matlab_test_case):
        """Per-cell CMC flags must match the MATLAB reference."""
        tc = matlab_test_case
        cells, params, center = build_test_params(tc["inputs"])

        result = classify_congruent_cells(cells, params, center)

        expected_flags = tc["outputs"]["vbVal"]
        if isinstance(expected_flags, bool):
            expected_flags = [expected_flags]
        actual_flags = [c.is_congruent for c in result.cells]
        assert actual_flags == expected_flags, (
            f"[{tc['name']}] CMC flags mismatch:\n"
            f"  expected: {expected_flags}\n"
            f"  actual:   {actual_flags}"
        )

    def test_consensus_rotation(self, matlab_test_case):
        """The consensus rotation must match the MATLAB rAngle."""
        tc = matlab_test_case
        cells, params, center = build_test_params(tc["inputs"])

        result = classify_congruent_cells(cells, params, center)

        expected_angle = tc["outputs"]["rAngle"]
        actual_angle = result.consensus_rotation
        if np.isnan(expected_angle):
            assert np.isnan(actual_angle), (
                f"[{tc['name']}] Expected NaN consensus rotation, got {actual_angle}"
            )
        else:
            np.testing.assert_allclose(
                actual_angle,
                expected_angle,
                atol=ANGLE_ATOL,
                err_msg=f"[{tc['name']}] Consensus rotation mismatch",
            )

    def test_consensus_translation(self, matlab_test_case):
        """The consensus translation must match the MATLAB vTrans."""
        tc = matlab_test_case
        cells, params, center = build_test_params(tc["inputs"])

        result = classify_congruent_cells(cells, params, center)

        expected_trans = as_array(tc["outputs"]["vTrans"])
        actual_trans = np.asarray(result.consensus_translation)
        if np.all(np.isnan(expected_trans)):
            assert np.all(np.isnan(actual_trans)), (
                f"[{tc['name']}] Expected NaN translation, got {actual_trans}"
            )
        else:
            np.testing.assert_allclose(
                actual_trans,
                expected_trans,
                atol=TRANSLATION_ATOL,
                err_msg=f"[{tc['name']}] Consensus translation mismatch",
            )


# ---------------------------------------------------------------------------
# Named scenario tests
# ---------------------------------------------------------------------------


class TestSpecificScenarios:
    """
    Named tests for each scenario, useful for quick debugging of
    individual failure modes.
    """

    @staticmethod
    def _get_case(name: str) -> dict:
        for tc in _TEST_CASES:
            if tc["name"] == name:
                return tc
        raise ValueError(f"Test case '{name}' not found")

    def test_all_congruent_no_outliers(self):
        """All cells share a consistent transformation — all should be CMC."""
        # Arrange
        cells, params, center = build_test_params(
            self._get_case("all_congruent_no_outliers")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, center)

        # Assert
        assert all(c.is_congruent for c in result.cells)
        assert result.cmc_count == 6

    def test_low_similarity_rejected(self):
        """Cells below the correlation threshold must not be classified as CMC."""
        # Arrange
        cells, params, center = build_test_params(
            self._get_case("low_similarity_cells")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, center)

        # Assert — cells at index 1 and 3 have simVal 0.2 and 0.15 (below 0.4)
        assert not result.cells[1].is_congruent
        assert not result.cells[3].is_congruent
        assert result.cmc_count == 4

    def test_esd_rejects_angle_outliers(self):
        """ESD outlier rejection should remove cells with aberrant angles."""
        # Arrange
        cells, params, center = build_test_params(
            self._get_case("angle_outliers_esd_rejection")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, center)

        # Assert — cells 3 and 7 (0-indexed: 2 and 6) are angle outliers
        assert not result.cells[2].is_congruent
        assert not result.cells[6].is_congruent
        assert result.cmc_count == 6

    def test_position_outliers_rejected(self):
        """Cells with large position residuals must be rejected."""
        # Arrange
        cells, params, center = build_test_params(
            self._get_case("position_outliers")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, center)

        # Assert — cells 2 and 5 (0-indexed: 1 and 4) have large position errors
        assert not result.cells[1].is_congruent
        assert not result.cells[4].is_congruent
        assert result.cmc_count == 4

    def test_no_valid_cells(self):
        """When all cells are below similarity threshold, zero CMCs result."""
        # Arrange
        cells, params, center = build_test_params(
            self._get_case("no_valid_cells")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, center)

        # Assert
        assert not any(c.is_congruent for c in result.cells)

    def test_mixed_outliers(self):
        """Mixed failure modes: similarity, angle, and position outliers."""
        # Arrange
        cells, params, center = build_test_params(
            self._get_case("mixed_outliers")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, center)

        # Assert — cell 2 (idx 1): low sim, cell 4 (idx 3): angle, cell 8 (idx 7): pos
        assert not result.cells[1].is_congruent
        assert not result.cells[3].is_congruent
        assert not result.cells[7].is_congruent
        assert result.cmc_count == 7

    def test_single_cell(self):
        """A single valid cell should be classified as CMC."""
        # Arrange
        cells, params, center = build_test_params(
            self._get_case("single_cell")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, center)

        # Assert
        assert result.cells[0].is_congruent

    def test_all_angle_outliers_no_cmc(self):
        """When all angles are wildly scattered, ESD + filtering yields 0 CMC."""
        # Arrange
        cells, params, center = build_test_params(
            self._get_case("all_angle_outliers")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, center)

        # Assert
        assert not any(c.is_congruent for c in result.cells)

    def test_nan_similarity_handled(self):
        """Cells with NaN similarity (failed registration) must not be CMC."""
        # Arrange
        cells, params, center = build_test_params(
            self._get_case("nan_similarity_values")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, center)

        # Assert — cells 2 and 5 (0-indexed: 1 and 4) have NaN similarity
        assert not result.cells[1].is_congruent
        assert not result.cells[4].is_congruent
        assert result.cmc_count == 4
