"""
Tests for cmc_classification.classify_congruent_cells using test vectors
generated by MATLAB's cell_cmc_median (procedure 6).

The MATLAB reference is cell_cmc_median.m with:
  - Generalised ESD outlier rejection on cell angles
  - Median-based consensus angle and translation estimation
  - Final classification by similarity, angle, and position thresholds
"""

import json
from pathlib import Path

import numpy as np
import pytest

from conversion.surface_comparison.cmc_classification import classify_congruent_cells

from .helpers import build_test_inputs


TEST_ROOT = Path(__file__).parent.parent.parent
RESOURCES_DIR = TEST_ROOT / "resources"
TEST_DATA_PATH = RESOURCES_DIR / "cmc" / "classification" / "cmc_test_data.json"


ANGLE_ATOL = 1e-10
TRANSLATION_ATOL = 1e-10


def _load_test_cases() -> list[dict]:
    with open(TEST_DATA_PATH) as f:
        return json.load(f)


_TEST_CASES = _load_test_cases()
_TEST_IDS = [test_case["name"] for test_case in _TEST_CASES]


@pytest.fixture(params=_TEST_CASES, ids=_TEST_IDS)
def matlab_test_case(request) -> dict:
    return request.param


def _get_case(name: str) -> dict:
    for test_case in _TEST_CASES:
        if test_case["name"] == name:
            return test_case
    raise ValueError(f"Test case '{name}' not found")


class TestClassifyCongruentCells:
    """Test classify_congruent_cells against MATLAB cell_cmc_median procedure 6."""

    def test_cmc_count(self, matlab_test_case: dict) -> None:
        """The number of CMC cells must match the MATLAB reference."""
        cells, params, rotation_center = build_test_inputs(matlab_test_case["inputs"])

        result = classify_congruent_cells(cells, params, rotation_center)

        expected_cmc_count = matlab_test_case["outputs"]["cmc_count"]
        assert result.cmc_count == expected_cmc_count, (
            f"[{matlab_test_case['name']}] CMC count mismatch: "
            f"expected {expected_cmc_count}, got {result.cmc_count}"
        )

    def test_cmc_flags(self, matlab_test_case: dict) -> None:
        """Per-cell congruence flags must match the MATLAB reference."""
        cells, params, rotation_center = build_test_inputs(matlab_test_case["inputs"])

        result = classify_congruent_cells(cells, params, rotation_center)

        expected_flags = matlab_test_case["outputs"]["is_congruent"]
        if isinstance(expected_flags, bool):
            expected_flags = [expected_flags]
        actual_flags = [cell.is_congruent for cell in result.cells]
        assert actual_flags == expected_flags, (
            f"[{matlab_test_case['name']}] Congruence flags mismatch:\n"
            f"  expected: {expected_flags}\n"
            f"  actual:   {actual_flags}"
        )

    def test_consensus_rotation(self, matlab_test_case: dict) -> None:
        """The consensus rotation must match the MATLAB reference."""
        cells, params, rotation_center = build_test_inputs(matlab_test_case["inputs"])

        result = classify_congruent_cells(cells, params, rotation_center)

        expected_rotation = matlab_test_case["outputs"]["consensus_rotation_deg"]
        if np.isnan(expected_rotation):
            assert np.isnan(result.consensus_rotation), (
                f"[{matlab_test_case['name']}] Expected NaN consensus rotation, "
                f"got {result.consensus_rotation}"
            )
        else:
            np.testing.assert_allclose(
                result.consensus_rotation,
                expected_rotation,
                atol=ANGLE_ATOL,
                err_msg=f"[{matlab_test_case['name']}] Consensus rotation mismatch",
            )

    def test_consensus_translation(self, matlab_test_case: dict) -> None:
        """The consensus translation must match the MATLAB reference."""
        cells, params, rotation_center = build_test_inputs(matlab_test_case["inputs"])

        result = classify_congruent_cells(cells, params, rotation_center)

        expected_translation = matlab_test_case["outputs"]["consensus_translation"]
        actual_translation = result.consensus_translation
        if all(item is None for item in expected_translation):
            assert all(np.isnan(v) for v in actual_translation), (
                f"[{matlab_test_case['name']}] Expected NaN translation, "
                f"got {actual_translation}"
            )
        else:
            np.testing.assert_allclose(
                np.array(actual_translation),
                np.array(expected_translation),
                atol=TRANSLATION_ATOL,
                err_msg=f"[{matlab_test_case['name']}] Consensus translation mismatch",
            )


class TestSpecificScenarios:
    """Named tests per scenario, useful for targeted debugging of failure modes."""

    def test_all_congruent_no_outliers(self) -> None:
        """All cells share a consistent transformation — all should be CMC."""
        # Arrange
        cells, params, rotation_center = build_test_inputs(
            _get_case("all_congruent_no_outliers")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, rotation_center)

        # Assert
        assert all(cell.is_congruent for cell in result.cells)
        assert result.cmc_count == 6

    def test_low_similarity_rejected(self) -> None:
        """Cells below the correlation threshold must not be classified as CMC."""
        # Arrange
        cells, params, rotation_center = build_test_inputs(
            _get_case("low_similarity_cells")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, rotation_center)

        # Assert — cells at index 1 and 3 have scores 0.2 and 0.15 (below threshold 0.4)
        assert not result.cells[1].is_congruent
        assert not result.cells[3].is_congruent
        assert result.cmc_count == 4

    def test_esd_rejects_angle_outliers(self) -> None:
        """ESD outlier rejection should remove cells with aberrant angles."""
        # Arrange
        cells, params, rotation_center = build_test_inputs(
            _get_case("angle_outliers_esd_rejection")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, rotation_center)

        # Assert — cells at index 2 and 6 are angle outliers (~29° and ~-23°)
        assert not result.cells[2].is_congruent
        assert not result.cells[6].is_congruent
        assert result.cmc_count == 6

    def test_position_outliers_rejected(self) -> None:
        """Cells with large position residuals must be rejected."""
        # Arrange
        cells, params, rotation_center = build_test_inputs(
            _get_case("position_outliers")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, rotation_center)

        # Assert — cells at index 1 and 4 exceed the position threshold
        assert not result.cells[1].is_congruent
        assert not result.cells[4].is_congruent
        assert result.cmc_count == 4

    def test_no_valid_cells(self) -> None:
        """When all cells are below the similarity threshold, zero CMCs result."""
        # Arrange
        cells, params, rotation_center = build_test_inputs(
            _get_case("no_valid_cells")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, rotation_center)

        # Assert
        assert not any(cell.is_congruent for cell in result.cells)

    def test_mixed_outliers(self) -> None:
        """Mixed failure modes: similarity, angle, and position outliers."""
        # Arrange
        cells, params, rotation_center = build_test_inputs(
            _get_case("mixed_outliers")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, rotation_center)

        # Assert — index 1: low score, index 3: angle outlier, index 7: position outlier
        assert not result.cells[1].is_congruent
        assert not result.cells[3].is_congruent
        assert not result.cells[7].is_congruent
        assert result.cmc_count == 7

    def test_single_cell(self) -> None:
        """A single valid cell should be classified as CMC."""
        # Arrange
        cells, params, rotation_center = build_test_inputs(
            _get_case("single_cell")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, rotation_center)

        # Assert
        assert result.cells[0].is_congruent

    def test_all_angle_outliers_yields_no_cmc(self) -> None:
        """When all angles are widely scattered, ESD and tightening yield 0 CMC."""
        # Arrange
        cells, params, rotation_center = build_test_inputs(
            _get_case("all_angle_outliers")["inputs"]
        )

        # Act
        result = classify_congruent_cells(cells, params, rotation_center)

        # Assert
        assert not any(cell.is_congruent for cell in result.cells)
